### PR TITLE
Replace Faraday with Excon

### PR DESCRIPTION
**Pull request by arvanasse**
Replaces Faraday as the http driver with Excon because Faraday exhibits SSL errors on current versions of OSX that are not present with Excon.  Ultimately this will allow conduit-suretax to be configured without relying on mock_status settings in development.

### CODE REVIEW

**Comment by mgates** [comment]
Is this the thing where it can't find the CA bundle with homebrew SSL - I had a friend who had this problem, I can figure out how he solved it, if that's it.

**Comment by arvanasse** [comment]
@mgates that's a possibility.  However, since all of our other communications libraries are based on Excon there seems little reason for this particular one to fight that battle just for the sake of using Faraday.

**Comment by mgates** [comment]
That seems reasonable :+1:

**Comment by arvanasse** [comment]
Merged #53

**Pull request merged**
